version: '3'
services:

  database:
    image: postgres:14.10-alpine
    restart: always
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - '5432:5432'
    volumes:
      - ./var/database/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
    external: true



